CREATE TABLE PRODUCTOS_Y (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    PRECIO NUMBER(10,2),
    CANTIDAD NUMBER
);

INSERT INTO PRODUCTOS_Y (NOMBRE, PRECIO, CANTIDAD)
VALUES ('Laptop', 3500, 10);

INSERT INTO PRODUCTOS_Y (NOMBRE, PRECIO, CANTIDAD)
VALUES ('Mouse', 80, 50);

INSERT INTO PRODUCTOS_Y (NOMBRE, PRECIO, CANTIDAD)
VALUES ('Teclado', 150, 30);

COMMIT;